const express = require('express');
const bodyParser = require('body-parser');
const { Client, Environment, ApiError } = require('square');

const app = express();
app.use(bodyParser.json());

const client = new Client({
    environment: Environment.Production, // or Environment.Production
    accessToken: 'EAAAlvd0owabWAkzKXlgauXdesy8ahHbIdJFMODM7leb7Z_SdXJv1RaQ84ZeuGmz',
});

app.post('/create-payment', async (req, res) => {
  const { sourceId } = req.body;  // The token generated by the frontend

  try {
    // Create a unique key for the payment request to prevent duplication
    const idempotencyKey = new Date().getTime().toString();

    // Call the Square Payments API to process the payment
    const paymentResponse = await paymentsApi.createPayment({
      sourceId,  // Use the token from the client
      idempotencyKey,  // Unique identifier for this transaction
      amountMoney: {
        amount: 15,  // Amount in cents (e.g., 1000 cents = $10.00)
        currency: 'USD',
      },
    });

    // If payment is successful, send success response
    res.status(200).json(paymentResponse);
  } catch (error) {
    // Handle errors and send error response
    console.error('Error processing payment:', error);
    res.status(500).json({ error: error.message });
  }
    });
  
  
app.use(express.static(__dirname))
app.listen(3000, () => {
    console.log('Server is running on http://localhost:3000');
});

module.exports = app;
